### ISSUE TITLE
Data.Array not found

### ISSUE THREAD

**Issue by afcondon** [pelotom/purescript-d3-examples#2]
Hi - would love to play with these examples but compile fails to find Data.Array for me (clean cloned repo, Mac OSX 10.9.4, psc "hello world" working fine, no bower errors). Seems like there should be something in the gulpfile to hook up the vendor/purescript-arrays/src/Data/Array.purs and other modules? or have i misconfigured something?

```
$ gulp
[10:30:05] Using gulpfile ~/work/Purescript/purescript-d3-examples/gulpfile.js
[10:30:05] Starting 'watch'...
[10:30:05] Starting 'copy-d3'...
[10:30:05] Starting 'clean-resources'...
[10:30:05] Starting 'compile'...
[10:30:05] Finished 'copy-d3' after 24 ms
[10:30:05] Finished 'clean-resources' after 19 ms
[10:30:05] Starting 'copy-resources'...
[10:30:05] Finished 'copy-resources' after 49 ms
[10:30:05] 'compile' errored after 205 ms
[10:30:05] Error: Error at /Users/afc/work/Purescript/purescript-d3-examples/src/BarChart3.purs line 5, column 1:
Error in module Graphics.D3.Examples.BarChart3
Cannot import unknown module 'Data.Array'

    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:161:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:187:15)
    at Gulp.emit (events.js:95:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/afc/work/Purescript/purescript-d3-examples/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/afc/work/Purescript/purescript-d3-examples/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/afc/work/Purescript/purescript-d3-examples/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/afc/work/Purescript/purescript-d3-examples/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at Transform.<anonymous> (/Users/afc/work/Purescript/purescript-d3-examples/gulpfile.js:27:5)
    at Transform.emit (events.js:117:20)
    at ChildProcess.<anonymous> (/Users/afc/work/Purescript/purescript-d3-examples/node_modules/gulp-purescript/index.js:93:24)
```

**Comment by Hi-Angel** [comment]
For future readers: nowadays you most likely are using `spargo` and the package missing is called `arrays` *(note the `s`)*. So:

```
$ spargo install arrays
```
