### ISSUE TITLE
bower issue?

### ISSUE THREAD

**Issue by tgdwyer** [pelotom/purescript-d3-examples#6]
```
$ npm install
npm WARN package.json purescript-d3-examples@ No repository field.

$ bower update
bower not-cached    git@github.com:pelotom/purescript-d3.git#master
bower resolve       git@github.com:pelotom/purescript-d3.git#master
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git@github.com:pelotom/purescript-d3.git", exit code of #128
```

but I'm not really familiar with bower so it's also possible I'm doing something stupid...

Thanks!

**Comment by pelotom** [comment]
It looks like it may be failing because you don't have an SSH key registered with GitHub for your computer. I should probably change the URL to use HTTP instead of SSH so that's not necessary...

**Comment by pelotom** [comment]
Let me know if it still doesn't work!

**Comment by tgdwyer** [comment]
I still had problems:
```
bash-3.1$ bower update
bower ENORESTARGET  URL sources can't resolve targets
```

Without really knowing what I was doing I tried changing the #master on the end of the URL in bower.json to .git
Then, bower went and cloned the purescript-d3 repository into bower_components... I assume that was the intention?

I still have a compile error though:
```
bash-3.1$ gulp
[00:00:45] Using gulpfile c:\Users\Tim\src\purescript-d3-examples\gulpfile.js
[00:00:45] Starting 'watch'...
[00:00:45] Starting 'copy-d3'...
[00:00:45] Starting 'clean-resources'...
[00:00:45] Starting 'compile'...
[00:00:46] Finished 'clean-resources' after 74 ms
[00:00:46] Starting 'copy-resources'...
[00:00:46] Finished 'copy-resources' after 73 ms
[00:00:46] Finished 'copy-d3' after 184 ms
[00:00:46] 'compile' errored after 473 ms
[00:00:46] Error: Error in module Graphics.D3.Examples.ForceLayout1:
Error at c:\Users\Tim\src\purescript-d3-examples\src\ForceLayout1.purs line 9, column 1 - line 10, column 1:
  Unknown module Graphics.D3.Layout.Base
See https://github.com/purescript/purescript/wiki/Error-Code-UnknownModule for more information, or to contribute content related to this error.


    at formatError (c:\Users\Tim\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (c:\Users\Tim\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at Gulp.emit (events.js:95:17)
    at Gulp.Orchestrator._emitTaskDone (c:\Users\Tim\src\purescript-d3-examples\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at c:\Users\Tim\src\purescript-d3-examples\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (c:\Users\Tim\src\purescript-d3-examples\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (c:\Users\Tim\src\purescript-d3-examples\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at Transform.<anonymous> (c:\Users\Tim\src\purescript-d3-examples\gulpfile.js:27:5)
    at Transform.emit (events.js:117:20)
    at ChildProcess.<anonymous> (c:\Users\Tim\src\purescript-d3-examples\node_modules\gulp-purescript\index.js:93:24)
```

I'm afraid I'm a bit of a newbie at purescript also, so I might be being silly?
